[package]
name = "magma_api"
version = "0.0.0"
edition = "2021"
license = "MIT"
description = "API of the Magma3D game engine"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
magma_app = { path = "crates/magma_app" }                      # add version
magma_audio = { path = "crates/magma_audio", optional = true } # add version

[workspace]
members = ["crates/*"]

[features]
default = ["audio"]

audio = ["dep:magma_audio"]
